# generated by datamodel-codegen:
#   filename:  fleet_log_update.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field

from . import fleet_log


class Type16(Enum):
    fleet_log_update = 'fleet_log_update'


class TaskEventLogUpdate(BaseModel):
    type: Type16 = Field(..., description='Indicate that this is a fleet log update')
    data: fleet_log.FleetLog
