# generated by datamodel-codegen:
#   filename:  fleet_log_request.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Type6(Enum):
    fleet_log_request = 'fleet_log_request'


class FleetLogRequest(BaseModel):
    type: Type6 = Field(..., description='Indicate that this is a fleet log request')
    fleet: str = Field(
        ..., description='Specify the name of the fleet whose log should be fetched'
    )
