# generated by datamodel-codegen:
#   filename:  resume_task_request.json

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Type11(Enum):
    resume_task_request = 'resume_task_request'


class TaskResumeRequest(BaseModel):
    type: Optional[Type11] = Field(
        None, description='Indicate that this is a task resuming request'
    )
    for_task: Optional[str] = Field(None, description='Specify task ID to resume.')
    for_tokens: Optional[List[str]] = Field(
        None,
        description='A list of tokens of interruption requests which should be resumed. The interruption request associated with each token will be discarded.',
        min_items=1,
        unique_items=True,
    )
    labels: Optional[List[str]] = Field(
        None, description='Labels describing this request'
    )
