# generated by datamodel-codegen:
#   filename:  task_log_request.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Type7(Enum):
    task_log_request = 'task_log_request'


class TaskLogRequest(BaseModel):
    type: Type7 = Field(..., description='Indicate that this is a task log request')
    task_id: str = Field(
        ..., description='Specify the ID of the task whose log should be fetched'
    )
