# generated by datamodel-codegen:
#   filename:  task_discovery_request.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Type10(Enum):
    task_discovery_request = 'task_discovery_request'


class TaskDiscoveryRequest(BaseModel):
    type: Type10 = Field(
        ..., description='Indicate that this is a task discovery request'
    )
